liongram/config/urls.py
from django.contrib import admin
from django.urls import path, include
# settings의 내용을 가져오는 코드
from django.conf import settings
from django.conf.urls.static import static

from posts.views import class_view, function_list_view, function_view, url_prameter_view, url_view, index

# Django에서 지원하는 변수(정규 표현식 대용인듯)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('url/', url_view),
    # 경로로 받기
    # path('url/<str:username>/', url_prameter_view),
    path('function_view/', function_view),
    path('class_view/', class_view.as_view()),
    path('function_view2/', function_list_view),

    # index 페이지 연결
    path('', index, name='index'),
    # liongram 하위에 만든 urls 내용들을 모두 연결시켜주는 코드
    path('posts/', include('posts.urls', namespace='posts')),
    path('support/', include('support.urls', namespace='support')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    # 배포 시 주석 처리
    # path('__debug__/', include('debug_toolbar.urls')),  
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

liongram/posts/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path

from posts.views import class_view, function_list_view, function_view, post_create_form_view, post_create_view, post_delete_view, post_detail_view, post_list_view, post_update_view, url_prameter_view, url_view, comment_create

app_name = 'posts'

urlpatterns = [
    path('', post_list_view, name='post_list'),
    path('create/', post_create_form_view, name='post-create'),
    # Django에서 지원하는 변수(정규 표현식 대용인듯)
    path('<int:id>', post_detail_view, name='post-detail'),
    path('<int:id>/edit/', post_update_view, name='post-edit'),
    path('<int:id>/delete/', post_delete_view, name='post-delete'),
    path('comment/<int:id>/create/', comment_create, name='comment-create'),

]

liongram/support/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path

from support.views import faq_create_view, faq_delete_view, faq_detail_view, faq_list_view, faq_update_view 

app_name = 'support'

urlpatterns = [
    path('', faq_list_view, name='faq_list'),
    path('new/', faq_create_view, name='faq_create'),
    # Django에서 지원하는 변수(정규 표현식 대용인듯)
    path('<int:id>', faq_detail_view, name='faq_detail'),
    path('<int:id>/edit/', faq_update_view, name='faq_modify'),
    path('<int:id>/delete/', faq_delete_view, name='faq_delete'),

]

liongram/support/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from config.models import BaseModel

# Create your models here.
User = get_user_model()

class Faq(BaseModel):

    class Category(models.TextChoices):
        GENERAL = 'GEN', _('General issue')
        ACCOUNT = 'ACC', _('Account issue')
        ETC = 'ETC', _('etc.')
        # PAYMENT = 'PAY', _('Payment')
        # POST = 'POST', _('Post')
        # DIRECTMESSAGE = 'DM', _('DirectMessage')
        # REELS = 'REEL', _('Reels')
        # CAMERAFILTER = 'FILT', _('CameraFilter')

    question = models.CharField(verbose_name='질문', max_length=64)
    category = models.CharField(max_length=3,
        choices=Category.choices,
        default=Category.GENERAL)
    faq_answer = models.TextField(verbose_name='답변',blank=True)
    created_by = models.ForeignKey(to=User, verbose_name='작성자', on_delete=models.CASCADE, related_name='faq_creater', blank=True, null=True)
    last_modified_by = models.ForeignKey(to=User, verbose_name='수정자', on_delete=models.CASCADE, related_name='faq_last_modifier', blank=True, null=True)


class Inquiry(BaseModel):
    class Category(models.TextChoices):
        GENERAL = 'GEN', _('General issue')
        ACCOUNT = 'ACC', _('Account issue')
        ETC = 'ETC', _('etc.')

    class Status(models.TextChoices):
        REGISTED = 'REG', _('문의 등록')
        CHECKING = 'CHE', _('접수 완료')
        COMPLETE = 'COM', _('답변 완료')
        NOTIFIED = 'NOT', _('알림 완료')

    category = models.CharField(max_length=3,
        choices=Category.choices,
        default=Category.GENERAL)
    


    title = models.CharField(verbose_name='질문 제목', max_length=64)
    status = models.CharField(max_length=3,
        choices=Status.choices,
        default=Status.REGISTED
    )
    email = models.EmailField(verbose_name='e-mail')
    email_checkbox = models.BooleanField(verbose_name='e-mail로 답변을 받겠습니다.')

    phone_number = models.CharField(verbose_name='전화번호', max_length=11)
    phone_checkbox = models.BooleanField(verbose_name='문자메시지로 답변을 받겠습니다.')
    detail = models.TextField(verbose_name='내용')

    image = models.ImageField(verbose_name='이미지', blank=True, null=True)
    dateTimeOfUpload = models.DateTimeField(auto_now = True)
    created_by = models.ForeignKey(to=User, verbose_name='작성자', on_delete=models.CASCADE, related_name='inquiry_creater', blank=True, null=True)
    last_modified_by = models.ForeignKey(to=User, verbose_name='수정자', on_delete=models.CASCADE, related_name='inquiry_last_modifier', blank=True, null=True)

class Answer(BaseModel):
    content = models.TextField(verbose_name='내용')
    # 외래키와 연동 및 종속되도록 설정
    Inquiry = models.ForeignKey(to='Inquiry', on_delete=models.CASCADE)
    # 사용자와 연결하기
    created_by = models.ForeignKey(to=User, verbose_name='작성자', on_delete=models.CASCADE, related_name='answer_creater', blank=True, null=True)
    last_modified_by = models.ForeignKey(to=User, verbose_name='수정자', on_delete=models.CASCADE, related_name='answer_last_modifier', blank=True, null=True)

liongram/support/views.py
from django.shortcuts import render
# from django.views.generic import ListView

from support.models import Faq

# Create your views here.
def index(request):
    return render(request, 'index.html')

def faq_list_view(request) :
    object_list = Faq.objects.all().order_by('-id')
    return render(request, 'support/FAQ_list.html', {'object_list' : object_list})

def faq_detail_view(request, id):
    # if request.method == 'POST' :
    #     Faq.question
    return render(request, 'support/FAQ_detail.html')

def faq_create_view(request):
    return render(request, 'support/FAQ_form.html')

def faq_update_view(request, id):
    return render(request, 'support/FAQ_form.html')

def faq_delete_view(request, id):
    return render(request, 'support/FAQ_confirm_delete.html')

liongram/templates/support/FAQ_confirm_delete.html
{% extends 'base.html' %}
{% block title %} FAQ {% endblock %}
{% block content %}

<a href="{% url 'support:faq_list' %}">게시글 목록</a>
<h1>FAQ</h1>
<form>
    <P>질문사항 <input type="text" name="title"></P>
</form>

{% endblock %}

liongram/templates/support/FAQ_detail.html
{% extends 'base.html' %}
{% block title %} FAQ {% endblock %}
{% block content %}

<a href="{% url 'support:faq_list' %}">게시글 목록</a>
<h1>FAQ</h1>
<form>
    <P>질문사항 <input type="text" name="title"></P>
</form>

{% endblock %}

liongram/templates/support/FAQ_form.html
{% extends 'base.html' %}
{% block title %} FAQ {% endblock %}
{% block content %}

    <h1>질문하기</h1>
    <p><a href="{% url 'support:faq_list' %}">목록</a></p>
    <form action="{% url 'support:faq_detail' %}" method="Post">
        {% csrf_token %}
        <!-- <P>제목 |</P> <p><input type="text" name="FAQ_title" size="64"></P> -->
        카테고리 : 
        <select name="choices">
            <option value="GEN">일반</option>
            <option value="ACC">계정</option>
            <option value="ETC">기타</option>
        </select>
        
        <P>질문 |</P> <p><textarea name="FAQ_question" cols="64" rows="5"></textarea></P>
        <P>답변 |</P> <p><textarea name="FAQ_answer" cols="64" rows="5"></textarea></P>

        <input type="submit" value="등록">

    </form>

{% endblock %}

liongram/templates/support/FAQ_list.html
{% extends 'base.html' %}
{% block title %} FAQ {% endblock %}
{% block content %}

<h1><a href="{% url 'support:faq_list' %}">FAQ 목록</a></h1>
<a href="{% url 'support:faq_create' %}">질문하기</a>
<!-- var a = {{ object_list }} -->

{% for object in object_list %}
    <li> {{object}}  </li>
{% endfor %}

{% endblock %}