liongram/config/urls.py
from django.contrib import admin
from django.urls import path, include
# settings의 내용을 가져오는 코드
from django.conf import settings
from django.conf.urls.static import static

from posts.views import class_view, function_list_view, function_view, url_prameter_view, url_view, index

# Django에서 지원하는 변수(정규 표현식 대용인듯)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('url/', url_view),
    # 경로로 받기
    # path('url/<str:username>/', url_prameter_view),
    path('function_view/', function_view),
    path('class_view/', class_view.as_view()),
    path('function_view2/', function_list_view),

    # index 페이지 연결
    path('', index, name='index'),
    # liongram 하위에 만든 urls 내용들을 모두 연결시켜주는 코드
    path('posts/', include('posts.urls', namespace='posts')),
    path('support/', include('support.urls', namespace='support')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    # 배포 시 주석 처리
    # path('__debug__/', include('debug_toolbar.urls')),  
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

liongram/posts/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path

from posts.views import class_view, function_list_view, function_view, post_create_form_view, post_create_view, post_delete_view, post_detail_view, post_list_view, post_update_view, url_prameter_view, url_view, comment_create

app_name = 'posts'

urlpatterns = [
    path('', post_list_view, name='post_list'),
    path('create/', post_create_form_view, name='post-create'),
    # Django에서 지원하는 변수(정규 표현식 대용인듯)
    path('<int:id>', post_detail_view, name='post-detail'),
    path('<int:id>/edit/', post_update_view, name='post-edit'),
    path('<int:id>/delete/', post_delete_view, name='post-delete'),
    path('comment/<int:id>/create/', comment_create, name='comment-create'),

]

liongram/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from config.models import BaseModel

# Create your models here.
User = get_user_model()

class Post(BaseModel) :
    image = models.ImageField(verbose_name='이미지', null=True, blank=True)
    content = models.TextField(verbose_name='내용')
    view_count = models.IntegerField(verbose_name='조회수', default=0)
    writer = models.ForeignKey(verbose_name='작성자', to=User, on_delete=models.CASCADE, null=True, blank=True)
    like = models.ManyToManyField(to=User, verbose_name='좋아요', blank=True, related_name='post_like')
    favorite = models.ManyToManyField(to=User, verbose_name='저장', blank=True, related_name='post_favorite')

class Comment(BaseModel) :
    content = models.TextField(verbose_name='내용')
    # 외래키와 연동 및 종속되도록 설정
    post = models.ForeignKey(to='Post', on_delete=models.CASCADE)
    # 사용자와 연결하기
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE)

liongram/posts/forms.py
from django import forms
from posts.models import Post



# class PostBaseForm(forms.Form):
#     CATEGORY_CHOICES =[
#         ('1', '일반'),
#         ('2', '계정'),
#     ]

#     image = forms.ImageField(label='이미지', required=True)
#     # text field는 따로 없음
#     content = forms.CharField(label='내용', widget=forms.Textarea, required=True)
#     # category = forms.ChoiceField(label='카테고리', choices=CATEGORY_CHOICES)

# ModelForm을 상속 받을 때는 Meta 클래스라는 걸 작성해줘야 함
class PostBaseForm(forms.ModelForm):
    
    class Meta :
        model = Post
        fields = '__all__'

from django.core.exceptions import ValidationError
class PostCreateForm(PostBaseForm):
    class Meta(PostBaseForm.Meta):
        fields = ['image', 'content']

    # clean_ + 필드 이름을 통해서 그 필드의 유효성을 검사하도록 한다는 것은 약속이래요..
    def clean_content(self) :
        data = self.cleaned_data['content']
        if '비속어' == data :
            raise ValidationError('\'비속어\'는 사용하실 수 없습니다.')
        
        return data

class PostUpdateForm(PostBaseForm):
    class Meta(PostBaseForm.Meta):
        fields = ['image', 'content']

class PostDetailForm(PostBaseForm):
    def __init__(self, *args, **kwargs):
        super(PostDetailForm, self).__init__(*args, **kwargs)
        # for field in self.fields :
            # field.widget.attrs['disabled'] = True
        for key in self.fields:
            self.fields[key].widget.attrs['disabled'] = True

liongram/posts/views.py
from csv import writer
from django.shortcuts import render, redirect, get_object_or_404 # 가져오거나 오류를 만든다
from django.http import Http404, HttpResponse, JsonResponse
from django.views.generic import ListView
from .models import Post, Comment
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from .forms import PostBaseForm, PostCreateForm, PostDetailForm
User = get_user_model()

# 인덱스 (사용자가 처음 들어왔을 때 보는 부분)
def index(request):
    post_list = Post.objects.all().order_by('-created_at')
    context = {
        'post_list' : post_list,
    }
    return render(request, 'index.html', context)

# 글 목록
def post_list_view(request):
    post_list = Post.objects.all()
    # Post.writer가 현재 로그인인 것만 조회
    # post_list = Post.objects.filter(writer=request.user)
    # render 함수의 3번째 인자가 context(딕셔너리)이기 때문에 코딩할 때도 웬만하면 규칙을 지켜서 진행
    context = {
        'post_list' : post_list,
    }
    return render(request, 'posts/post_list.html', context)

# 글 상세
def post_detail_view(request, id):
    try :
        post = Post.objects.get(id=id)

    except Post.DoesNotExist:
        return redirect('index')
    context = {
        'post' : post,
        # 'form' : PostDetailForm(),
    }
    return render(request, 'posts/post_detail.html', context)

# 로그인을 했을 때만 처리하는 함수라는 어노테이션
# 글 작성
@login_required
def post_create_view(request):
    # get으로 들어오면 폼을 보여주게 함
    if request.method == 'GET' :
        return render(request, 'posts/post_form.html')
    else :
        image = request.FILES.get('image')
        content = request.POST.get('content')
        Post.objects.create(
            image = image,
            content = content,
            writer = request.user
        )
        return redirect('index')

# 글 작성 (폼을 사용한 작업)
@login_required
def post_create_form_view(request):
    # get으로 들어오면 폼을 보여주게 함
    if request.method == 'GET' :
        # 양식 제공
        form = PostCreateForm()
        context = {
            'form' : form
        }
        return render(request, 'posts/post_form_2.html', context)
    else :
        # 양식 제공이 아니라 값을 줘야되니까 Form에 데이터 넣어줌
        form = PostCreateForm(request.POST, request.FILES)
        
        # image = request.FILES.get('image')
        # content = request.POST.get('content')

        # 유효성 검사를 해서 form 기반 제대로된 정보인지 확인 후 데이터 저장
        if form.is_valid() :
            Post.objects.create(
                image = form.cleaned_data['image'],
                content = form.cleaned_data['content'],
                writer = request.user
            )
        else :
            return redirect('posts:post-create')
        return redirect('index')

# 사용자가 로그인 되어 있을 때만, 글 수정 기능
@login_required
def post_update_view(request, id):
    # 아래 코드로 우측 코드를 대체할 수 있음 post = Post.objects.get(id=id)
    # 위 코드에서 does not exist Error가 났을 때 자동으로 404로 돌려주는 코드
    post = get_object_or_404(Post,id=id, writer=request.user)
    # if request.user != post.writer:
    #     raise Http404('잘못된 접근입니다.')
    if request.method == 'GET' :
        context = {
            'post' : post
        }
        return render(request, 'posts/post_form.html', context)
    elif request.method == 'POST':
        image = request.FILES.get('image')
        content = request.POST.get('content')

        if image :
            post.image.delete()
            post.image = image
        post.content = content
        post.save()
        return redirect('posts:post-detail', post.id )

# 사용자가 로그인 되어 있을 때만, 글 삭제 기능
@login_required
def post_delete_view(request, id):
    post = get_object_or_404(Post,id=id, writer=request.user)
    # if request.user != post.writer:
    #     raise Http404('잘못된 접근입니다.')
    if request.method == 'GET' :
        context = {
            'post' : post
        }
        return render(request, 'posts/post_confirm_delete.html', context)
    else :
        post.delete()
        return redirect('index')

# 사용자가 로그인 되어 있을 때만, 댓글 달기 기능
@login_required
def comment_create(request, id) :
    if request.method == 'POST' :
        # 게시글 가져오기
        post = get_object_or_404(Post, pk=id)
        # 댓글 내용 가져오기
        content = request.POST.get('content')
        
        if not content :
            context = {
                'message' : '댓글을 입력해주세요'
            }
            return render(render, 'post:post_list', context)
        else :
            Comment.objects.create(
                post = post,
                writer = request.user,
                content = content,
            )
    return redirect('index')

# 사용자가 로그인 되어 있을 때만, 좋아요 기능
@login_required
def post_like(request, id):
    # GET 으로 좋아요 반응을 보낸다고 가정하고
    if request.method == 'GET' :
        post = request.objects.get(id=id)
        user = request.user
        # 좋아요 수를 올린다.
        if user in post.like.all() :
            post.like.remove(user)
        else :
            post.like.add(user)


def url_view(request):
    print('url_view()')
    # return HttpResponse('<h1>url_view')
    data = {'code' : '001', 'msg' : 'OK'}
    return JsonResponse(data)

# Data를 받는 방법
def url_prameter_view(request, username) :
    print('url_prameter_view()')
    print(username)
    print(request.GET)
    return HttpResponse(username)

def function_view(request) :
    print(f'request.method : {request.method}')
    if (request.method == 'GET') :
        print(f'request.method : {request.GET}')
    if (request.method == 'POST') :
        print(f'request.method : {request.POST}')
    return render(request, 'view.html')


class class_view(ListView):
    model = Post
    template_name = 'cbv_view.html'

def function_list_view(request) :
    object_list = Post.objects.all().order_by('-id')

    return render(request, 'cbv_view.html', {'object_list' : object_list})

liongram/templates/mixin/posts/post_card.html
{% load static %}
<div class="card">
    <div class="card__header">
        <div class = card__user-image>
            {% if post.writer.profile_image != Null %}
                <img class="card__user-image" src="{{ post.writer.profile_image.url }}"/>
            {% else %}
                <img class="card__user-image" src="http://via.placeholder.com/32x32"/>
            {% endif %}
        </div>
        <a href="#">
            <!-- index 의 for문에서 돌아가고 있는 변수 post를 가져다 쓸 수 있음 -->
            <span class="card__user-name">&nbsp; {{ post.writer }}</span>
        </a>
        <!-- 현재 접속한 사람과 작성자가 같은 경우만 수정가능 -->
        {% if request.user == post.writer %}
            <a href="{% url 'posts:post-edit' post.id %}"> &emsp;수정하기&emsp; </a> |
            <a href="{% url 'posts:post-delete' post.id %}"> &emsp;삭제하기 </a>
        {% endif %}
    </div>
    <div class="card__body">
        <div>
            {% if post.image %}
                <img class="card__image" src="{{ post.image.url }}">
            {% else %}
                <img class="card__image" src="http://via/placeholder.com/600x600">
            {% endif %}
        </div>
        <div class="card__btn-group">
            <div>
                <img class="card__btn" src="{% static 'icons/favorite_outlined_black_36dp.svg' %}" alt="좋아요"/>
                <img class="card__btn" src="{% static 'icons/mode_comment_outlined_black_36dp.svg' %}" alt="댓글"/>
                <img class="card__btn" src="{% static 'icons/send_outlined_black_36dp.svg' %}" alt="공유하기"/>
            </div>
            <div>
                <img class="card__btn" src="{% static 'icons/bookmark_outlined_black_36dp.svg' %}" alt="북마크"/>
            </div>
        </div>
        <div class="card_content">
            <p class="card__like-num">좋아요 00개</p>
            <div class="card__main-text">
                <p><span
                        class="card__user-name">{{ post.writer }}&emsp;</span>
                        {% if not detail %}
                            {{ post.content |truncatechars:35 }} &nbsp;&nbsp;&nbsp;
                            <a href="{% url 'posts:post-detail' post.id %}">더 보기</a>
                        {% else %}
                            {{ post.content }}
                        {% endif %}
                </p>
            </div>
            <div>
                <form action="{% url 'posts:comment-create' id=post.id %}" method="POST" class="margin">
                    {% csrf_token %}
                    <input type="text" name="content" placeholder="댓글 달기...">
                    <input type="submit" value="댓글">
                </form>
                <!-- comment_set >> Post가 봤을 때 Comment의 입장 모델명_set (역참조 되고 있는 내용) -->
                <p class="space">댓글 {{ post.comment_set.all.count }} 개 &nbsp;&nbsp;&nbsp;
                    {% if not detail %}
                        <a href="{% url 'posts:post-detail' post.id %}">모두 보기</a>
                    {% endif %}
                </p>

                <ul class="card__comment-group">
                    {% if not detail %}
                        {% for comment in post.comment_set.all|slice:":2" %}
                            <p><span class="card__user-name">{{ comment.writer }}&emsp;</span>{{ comment.content }}</p>
                        {% endfor %}
                    {% else %}
                        {% for comment in post.comment_set.all %}
                            <p><span class="card__user-name">{{ comment.writer }}&emsp;</span>{{ comment.content }}</p>
                        {% endfor %}
                    {% endif %}
                </ul>
            </div>
            <span class="card__created-at">{{ post.created_at | date:"Y년 m월 d일" }}</span>
        </div>
    </div>
</div>