liongram/accounts/urls.py
from django.urls import path

from accounts.views import login_view, logout_view, signup_view, update_view

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('update/', update_view, name='update'),
    path('logout/', logout_view, name='logout'),

]

liongram/config/urls.py
from django.contrib import admin
from django.urls import path, include
# settings의 내용을 가져오는 코드
from django.conf import settings
from django.conf.urls.static import static

from posts.views import class_view, function_list_view, function_view, url_prameter_view, url_view, index

# Django에서 지원하는 변수(정규 표현식 대용인듯)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('url/', url_view),
    # 경로로 받기
    # path('url/<str:username>/', url_prameter_view),
    path('function_view/', function_view),
    path('class_view/', class_view.as_view()),
    path('function_view2/', function_list_view),

    # index 페이지 연결
    path('', index, name='index'),
    # liongram 하위에 만든 urls 내용들을 모두 연결시켜주는 코드
    path('posts/', include('posts.urls', namespace='posts')),
    path('support/', include('support.urls', namespace='support')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    # 배포 시 주석 처리
    # path('__debug__/', include('debug_toolbar.urls')),  
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

liongram/posts/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path

from posts.views import class_view, function_list_view, function_view, post_create_form_view, post_create_view, post_delete_view, post_detail_view, post_list_view, post_update_view, url_prameter_view, url_view, comment_create

app_name = 'posts'

urlpatterns = [
    path('', post_list_view, name='post_list'),
    path('create/', post_create_form_view, name='post-create'),
    # Django에서 지원하는 변수(정규 표현식 대용인듯)
    path('<int:id>', post_detail_view, name='post-detail'),
    path('<int:id>/edit/', post_update_view, name='post-edit'),
    path('<int:id>/delete/', post_delete_view, name='post-delete'),
    path('comment/<int:id>/create/', comment_create, name='comment-create'),

]

liongram/support/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path

from support.views import faq_create_view, faq_delete_view, faq_detail_view, faq_list_view, faq_update_view 

app_name = 'support'

urlpatterns = [
    path('', faq_list_view, name='faq_list'),
    path('new/', faq_create_view, name='faq_create'),
    # Django에서 지원하는 변수(정규 표현식 대용인듯)
    path('<int:id>', faq_detail_view, name='faq_detail'),
    path('<int:id>/edit/', faq_update_view, name='faq_modify'),
    path('<int:id>/delete/', faq_delete_view, name='faq_delete'),

]

liongram/templates/base.html
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %} | 라이언그램</title>
    <link rel="stylesheet" href="{% static 'reset.css' %}">
    <link rel="stylesheet" href="{% static 'index.css' %}">
    {% block css %}{% endblock %}
</head>
<body class="container">
    <div>
        <nav>
            <ul class="top-menu-group">
                {% if request.user.is_authenticated %}
                    <li>안녕하세요 {{ request.user.username }} 님 
                    <li><a href="{% url 'accounts:logout' %}"> 로그아웃</a></li>
                    
                {% else %}
                    Guest 모드 입니다.
                    <li><a href="{% url 'accounts:login' %}"> 로그인</a></li>
                    <li><a href="{% url 'accounts:signup' %}"> 회원가입</a></li>
                    
                {% endif %}
            </ul>
        </nav>
    </div>
    <br>
    <br>
<div>
    {% block content %}
    {% endblock %}
</div>
<div>
    <nav>
        <ul class="bottom-menu-group">
            <li>
                <a href="{% url 'index' %}">
                    <img src="{% static 'icons/home_outlined_black_36dp.svg' %}" alt="홈">
                </a>
            </li>
            <li>
                <a>
                    <img src="{% static 'icons/search_outlined_black_36dp.svg' %}" alt="검색">
                </a>
            </li>
            <li>
                <a href="{% url 'posts:post-create' %}">
                    <img src="{% static 'icons/add_box_outlined_black_36dp.svg' %}" alt="글쓰기">
                </a>
            </li>
            <li>
                <a href="{% url 'index' %}">
                    <img src="{% static 'icons/favorite_outlined_black_36dp.svg' %}" alt="좋아요">
                </a>
            </li>
            <li>
                <a href="{% url 'accounts:update' %}">
                    <img src="{% static 'icons/account_circle_outlined_black_36dp.svg' %}" alt="내 페이지">
                </a>
            </li>
        </ul>
    </nav>
</div>

{% block script %}{% endblock %}
</body>
</html>

liongram/templates/index.html
{% extends 'base.html' %}
{% block title %} 인덱스 {% endblock %}
{% block content %}

<!-- <ul>
    <li><a href="{% url 'posts:post_list' %}">게시글 목록</a></li>
    <li><a href="{% url 'support:faq_list' %}">FAQ</a></li>
</ul> -->
<main>
    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
    <div class="card-list">
        <div class="card">
            {% for post in post_list %}
                {% include 'mixin/posts/post_card.html' with detail=False %}
            {% endfor %}
        </div>
    </div>

</main>
{% endblock %}